CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FISRT_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT OR IGNORE INTO telegram_users VALUES (?,?,?,?,?)"""

CREATE_CALLBACK_QUERY = """
CREATE TABLE IF NOT EXISTS callback_query
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
ANSWER TEXT DEFAULT NULL,
UNIQUE (TELEGRAM_ID),
FOREIGN KEY (TELEGRAM_ID) REFERENCES telegram_users(TELEGRAM_ID)
)
"""
INSERT_CALLBACK_QUERY = """
INSERT OR IGNORE INTO callback_query VALUES (?, ?, ?)"""

CREATE_BAN_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS ban_users
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
COUNT INTEGER,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_BAN_USER_QUERY = """
INSERT INTO ban_users VALUES (?,?,?)
"""

SELECT_BAN_USER_QUERY = """
SELECT * FROM ban_users WHERE TELEGRAM_ID = ?
"""

UPDATE_BAN_USER_COUNT_QUERY = """
UPDATE ban_users SET COUNT = COUNT + 1 WHERE TELEGRAM_ID = ?
"""

CREATE_USER_DATA_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS user_data
(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(10),
AGE INTEGER,
GENDER CHAR(50),
LOCATION TEXT,
BIO CHAR(200),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_DATA_QUERY = """
INSERT INTO user_data VALUES (?,?,?,?,?,?,?,?)
"""